
// This file was auto-generated by ML.NET Model Builder. 

using MlConsoleApp2;

Console.WriteLine("Вязкость конечного шлака при температуре 1500 °С");
Console.WriteLine("Введите дату в формате ДД.ММ.ГГГГ");
string data = Console.ReadLine();


// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Date = data,
  
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine($"\n\nПрогнозируемое количество: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();
